FROM --platform=linux/amd64 hyperledger/sawtooth-shell:chime

# install python3 + pip
RUN apt-get update && \
    apt-get install -y --no-install-recommends python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

# install intkey client
RUN pip3 install --no-cache-dir sawtooth-intkey
